### ISSUE TITLE
bug(camera):  Camera.requestPermissions() hangs on Android 33+

### ISSUE THREAD

**Issue by stefanMinch3v** [ionic-team/capacitor-plugins#2140]
### Capacitor Version

6

### Platforms Affected

- [ ] iOS
- [X] Android
- [ ] Web

### Current Behavior

When I click the button to pick an image from the gallery nothing happens

### Expected Behavior

When i click the button to pick an image from the gallery it shows a pop-up to allow reading images and then select the image

### Project Reproduction

https://github.com/stefanMinch3v/capacitor-bug-image-gallery/tree/main

### Additional Information

On capacitor 5 the code below works as expected. It requests permission to read from gallery and then shows the gallery to pick an image. With capacitor 6, on button click nothing happens

With only these 2 permissions in the AndroidManifest.xml file
uses-permission android:name="android.permission.READ_MEDIA_IMAGES"
 uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"

Android version tested - 12 (works here), 13 (not working) and 14 (not working)

`async selectImage(): Promise<void> {

    try {
      await Camera.requestPermissions();
    } catch {
      // do nothing
    }

    let img: Photo = null;

    try {
      img = await Camera.getPhoto({
        quality: 90,
        allowEditing: false,
        resultType: CameraResultType.Base64,
        source: CameraSource.Photos
      });
    } catch {
      // cancel image from gallery
    }

    if (img) {
     // continue the flow below
    }
  }`
  
  Any idea how should I proceed here, do I need to add some extra code or permissions to the manifest file?
  Thank you

**Comment by botrot** [comment]
Is it safe to use without requesting permissions to read from camera/gallery, I thought it should always ask the user.

**Comment by OS-pedrogustavobilro** [comment]
Hey everyone, this issue was fixed in [camera plugin version 7.0.2](https://github.com/ionic-team/capacitor-plugins/releases/tag/%40capacitor%2Fcamera%407.0.2).

Closing this issue. Thank you!

**Comment by LukasGrubis** [comment]
Still not working on Android version 11, its not supported anymore?

**Comment by OS-pedrogustavobilro** [comment]
Hey @LukasGrubis, on my end I'm not having any issues with `Camera.requestPermissions()` on the latest version, including on Android 11, can you describe what problem you are experiencing?

**Comment by LukasGrubis** [comment]
It still isn’t behaving correctly.
Example:

```
const checkPermissionResponse = Camera.checkPermissions();
```

<img width="319" height="149" alt="Image" src="https://github.com/user-attachments/assets/0c4de895-49c2-40aa-9a22-99ca27d7060e" />

Even when permissions are already granted, `await Camera.requestPermissions({ permissions: ['photos'] })` should at least return the current status and not hang, blocking any subsequent code.

**Comment by OS-pedrogustavobilro** [comment]
@LukasGrubis, I am not able to reproduce what you are mentioning on any Android version with the latest version of the Camera Plugin and Capacitor 7. It could be you're experiencing a different problem.

I recommend opening a new issue with additional details.

Thanks!
